trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install bandit
  displayName: 'Bandit Installation'

- script: ls
  displayName: 'Bandit Scan'

- script: cd ..
  displayName: 'Bandit Scan'

- script: ls
  displayName: 'Bandit Scan'

- script: bandit -r /python-webapp
  displayName: 'Bandit Scan'