trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install safety
  displayName: 'Safety Installation'

- script: |
    safety check --key $(safety_api_key)

# - task: CopyFiles@2
#   inputs:
#     Contents: 'safetyCheckReports.txt'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'Safety_scan_result'
#     publishLocation: 'Container'
