trigger:
- main

pool:
  vmImage: ubuntu-latest

- script: pip install safety
  displayName: 'Safety Installation'

- script: |
    safety check --key $(safety_api_key) | tee safetyCheckReports.txt
    cat safetyCheckReports.txt

# - task: CopyFiles@2
#   inputs:
#     Contents: '*.json'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'Bandit_scan_result'
#     publishLocation: 'Container'
