trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install bandit
  displayName: 'Bandit Installation'

- script: bandit -r ./ | tee banditResult.json
  displayName: 'Bandit Scan'

- script: cat banditResult.json
  displayName: 'View Scan Result'