trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install bandit
  displayName: 'Bandit Installation'

- script: |
    bandit -r ./ -f json --output banditResult.json
    cat banditResult.json
  displayName: 'Run a multi-line script'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'job/s/*.json'
    publishLocation: 'pipeline'