trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install bandit
  displayName: 'Bandit Installation'

- script: |
    bandit -r ./ -f json --output banditResult.json
    cat banditResult.json
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
