version: 0.2
env:
  parameter-store:
     SAFETY_API_KEY: "SAFETY_API_KEY"
phases:
  install:
    commands:
      - echo Installing Safety
      - pip install safety
  build:
    commands:
      - echo Scanning Repo
      - safety check requirements.txt --key "$SAFETY_API_KEY"
  post_build:
    commands:
      - echo Scanned Results!!!
  
# artifacts:
#   files:
#   - '*.json'
#   name: ${CODEBUILD_BUILD_ID}-$(TZ=$TZ date +'%Y-%m-%d_%H-%M-%S')
